author: Pro_Nil
main: me.pronil.Main
version: 1.5
name: Bedwars1058-ArenaStartMessage
softdepend: [ BedWars1058, BedWarsProxy]
commands:
  ArenaStartMessagereload:
    description: reload the config
